Expose public api that allows customization of Notifications' style class
controlsfx/controlsfx pull request #1424
Opened 2022-03-09 08:27 UTC by RationalityFrontline

Fix #1423

2022-03-19 17:53 UTC, Maxoudela requested changes
Please update the last year to `2022` in the copyright of the file.

2022-03-19 17:53 UTC, Maxoudela commented on controlsfx/src/main/java/org/controlsfx/control/Notifications.java
> +import java.util.*;
Prefer importing what you need explicitly rather than the `*`

2022-03-19 17:53 UTC, Maxoudela commented on controlsfx/src/main/java/org/controlsfx/control/Notifications.java
> +     * Specify the style classes to add to the {@link NotificationBar}.
As per Oracle recommendation: "Use 3rd person (descriptive) not 2nd person (prescriptive)." -> [source](https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html)

So better to go for "Specifies" I guess

2022-03-19 17:53 UTC, Maxoudela commented on controlsfx/src/main/java/org/controlsfx/control/Notifications.java
> +    public List<String> getStyleClass() {
Missing javadoc 😃

2022-03-20 10:48 UTC, Maxoudela approved these changes

2022-03-20 17:50 UTC, abhinayagarwal commented
Hi @RationalityFrontline ,

Can you please [replace 2021 with 2022 in the license header](https://github.com/controlsfx/controlsfx/blob/d5a569a9bcf157f8b8849f14f6662af2620a7312/controlsfx/src/main/java/org/controlsfx/control/Notifications.java#L2)?

2022-03-21 01:00 UTC, RationalityFrontline commented
> Hi @RationalityFrontline ,
> 
> Can you please [replace 2021 with 2022 in the license header](https://github.com/controlsfx/controlsfx/blob/d5a569a9bcf157f8b8849f14f6662af2620a7312/controlsfx/src/main/java/org/controlsfx/control/Notifications.java#L2)?

Updated.

2022-03-21 04:59 UTC, abhinayagarwal approved these changes

2022-03-21 04:59 UTC, merged